// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/analytics" | "/admin/analytics/costs" | "/admin/analytics/customers" | "/admin/analytics/revenue" | "/admin/analytics/washers" | "/admin/audit" | "/admin/corporate" | "/admin/customers" | "/admin/disputes" | "/admin/exports" | "/admin/fees" | "/admin/inventory" | "/admin/locations" | "/admin/locations/[id]" | "/admin/packages" | "/admin/services" | "/admin/settings" | "/admin/staff" | "/admin/subscriptions" | "/book" | "/book/emergency" | "/bookings" | "/bookings/[id]" | "/bookings/[id]/chat" | "/bookings/[id]/track" | "/cars" | "/cars/[id]" | "/cars/new" | "/dashboard" | "/forgot-password" | "/login" | "/loyalty" | "/manager/dashboard" | "/manager/disputes" | "/manager/inventory" | "/manager/offers" | "/manager/schedule" | "/manager/staff" | "/notifications" | "/offers" | "/packages" | "/packages/[id]" | "/payments" | "/profile" | "/register" | "/sign-in/[[...sign-in]]" | "/sign-up/[[...sign-up]]" | "/subscribe/[packageId]" | "/subscriptions" | "/survey/[bookingId]" | "/washer/availability" | "/washer/bookings/[id]" | "/washer/chat/[bookingId]" | "/washer/performance" | "/washer/queue" | "/washer/upsell/[bookingId]" | "/washer/wash/[bookingId]/start" | "/washer/wash/[sessionId]" | "/washer/wash/[sessionId]/complete"
type AppRouteHandlerRoutes = "/api/analytics/revenue" | "/api/exports" | "/api/locale" | "/api/locations/[id]/availability" | "/api/scheduling/generate" | "/api/subscribe" | "/api/webhooks/mercadopago" | "/api/webhooks/stripe"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/analytics": {}
  "/admin/analytics/costs": {}
  "/admin/analytics/customers": {}
  "/admin/analytics/revenue": {}
  "/admin/analytics/washers": {}
  "/admin/audit": {}
  "/admin/corporate": {}
  "/admin/customers": {}
  "/admin/disputes": {}
  "/admin/exports": {}
  "/admin/fees": {}
  "/admin/inventory": {}
  "/admin/locations": {}
  "/admin/locations/[id]": { "id": string; }
  "/admin/packages": {}
  "/admin/services": {}
  "/admin/settings": {}
  "/admin/staff": {}
  "/admin/subscriptions": {}
  "/api/analytics/revenue": {}
  "/api/exports": {}
  "/api/locale": {}
  "/api/locations/[id]/availability": { "id": string; }
  "/api/scheduling/generate": {}
  "/api/subscribe": {}
  "/api/webhooks/mercadopago": {}
  "/api/webhooks/stripe": {}
  "/book": {}
  "/book/emergency": {}
  "/bookings": {}
  "/bookings/[id]": { "id": string; }
  "/bookings/[id]/chat": { "id": string; }
  "/bookings/[id]/track": { "id": string; }
  "/cars": {}
  "/cars/[id]": { "id": string; }
  "/cars/new": {}
  "/dashboard": {}
  "/forgot-password": {}
  "/login": {}
  "/loyalty": {}
  "/manager/dashboard": {}
  "/manager/disputes": {}
  "/manager/inventory": {}
  "/manager/offers": {}
  "/manager/schedule": {}
  "/manager/staff": {}
  "/notifications": {}
  "/offers": {}
  "/packages": {}
  "/packages/[id]": { "id": string; }
  "/payments": {}
  "/profile": {}
  "/register": {}
  "/sign-in/[[...sign-in]]": { "sign-in"?: string[]; }
  "/sign-up/[[...sign-up]]": { "sign-up"?: string[]; }
  "/subscribe/[packageId]": { "packageId": string; }
  "/subscriptions": {}
  "/survey/[bookingId]": { "bookingId": string; }
  "/washer/availability": {}
  "/washer/bookings/[id]": { "id": string; }
  "/washer/chat/[bookingId]": { "bookingId": string; }
  "/washer/performance": {}
  "/washer/queue": {}
  "/washer/upsell/[bookingId]": { "bookingId": string; }
  "/washer/wash/[bookingId]/start": { "bookingId": string; }
  "/washer/wash/[sessionId]": { "sessionId": string; }
  "/washer/wash/[sessionId]/complete": { "sessionId": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
