// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(admin)/admin/analytics/costs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics/costs">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/analytics/costs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/analytics/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics/customers">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/analytics/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/analytics/revenue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics/revenue">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/analytics/revenue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/analytics/washers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics/washers">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/analytics/washers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/corporate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/corporate">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/corporate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/customers">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/disputes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/disputes">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/disputes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/exports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/exports">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/exports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/fees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/fees">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/fees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inventory">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/locations/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/locations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/locations/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/locations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/locations">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/locations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/packages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/packages">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/packages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/services">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/staff">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/subscriptions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/subscriptions">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/subscriptions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(customer)/book/emergency/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book/emergency">> = Specific
  const handler = {} as typeof import("../../src/app/(customer)/book/emergency/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(customer)/book/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book">> = Specific
  const handler = {} as typeof import("../../src/app/(customer)/book/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(customer)/bookings/[id]/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bookings/[id]/chat">> = Specific
  const handler = {} as typeof import("../../src/app/(customer)/bookings/[id]/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(customer)/bookings/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bookings/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(customer)/bookings/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(customer)/bookings/[id]/track/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bookings/[id]/track">> = Specific
  const handler = {} as typeof import("../../src/app/(customer)/bookings/[id]/track/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(customer)/bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bookings">> = Specific
  const handler = {} as typeof import("../../src/app/(customer)/bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(customer)/cars/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cars/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(customer)/cars/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(customer)/cars/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cars/new">> = Specific
  const handler = {} as typeof import("../../src/app/(customer)/cars/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(customer)/cars/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cars">> = Specific
  const handler = {} as typeof import("../../src/app/(customer)/cars/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(customer)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(customer)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(customer)/loyalty/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/loyalty">> = Specific
  const handler = {} as typeof import("../../src/app/(customer)/loyalty/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(customer)/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/(customer)/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(customer)/offers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offers">> = Specific
  const handler = {} as typeof import("../../src/app/(customer)/offers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(customer)/packages/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/packages/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(customer)/packages/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(customer)/packages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/packages">> = Specific
  const handler = {} as typeof import("../../src/app/(customer)/packages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(customer)/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payments">> = Specific
  const handler = {} as typeof import("../../src/app/(customer)/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(customer)/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/(customer)/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(customer)/subscribe/[packageId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subscribe/[packageId]">> = Specific
  const handler = {} as typeof import("../../src/app/(customer)/subscribe/[packageId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(customer)/subscriptions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subscriptions">> = Specific
  const handler = {} as typeof import("../../src/app/(customer)/subscriptions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(customer)/survey/[bookingId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/survey/[bookingId]">> = Specific
  const handler = {} as typeof import("../../src/app/(customer)/survey/[bookingId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(manager)/manager/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(manager)/manager/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(manager)/manager/disputes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager/disputes">> = Specific
  const handler = {} as typeof import("../../src/app/(manager)/manager/disputes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(manager)/manager/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager/inventory">> = Specific
  const handler = {} as typeof import("../../src/app/(manager)/manager/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(manager)/manager/offers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager/offers">> = Specific
  const handler = {} as typeof import("../../src/app/(manager)/manager/offers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(manager)/manager/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager/schedule">> = Specific
  const handler = {} as typeof import("../../src/app/(manager)/manager/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(manager)/manager/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager/staff">> = Specific
  const handler = {} as typeof import("../../src/app/(manager)/manager/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(washer)/washer/availability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/washer/availability">> = Specific
  const handler = {} as typeof import("../../src/app/(washer)/washer/availability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(washer)/washer/bookings/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/washer/bookings/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(washer)/washer/bookings/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(washer)/washer/chat/[bookingId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/washer/chat/[bookingId]">> = Specific
  const handler = {} as typeof import("../../src/app/(washer)/washer/chat/[bookingId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(washer)/washer/performance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/washer/performance">> = Specific
  const handler = {} as typeof import("../../src/app/(washer)/washer/performance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(washer)/washer/queue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/washer/queue">> = Specific
  const handler = {} as typeof import("../../src/app/(washer)/washer/queue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(washer)/washer/upsell/[bookingId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/washer/upsell/[bookingId]">> = Specific
  const handler = {} as typeof import("../../src/app/(washer)/washer/upsell/[bookingId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(washer)/washer/wash/[bookingId]/start/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/washer/wash/[bookingId]/start">> = Specific
  const handler = {} as typeof import("../../src/app/(washer)/washer/wash/[bookingId]/start/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(washer)/washer/wash/[sessionId]/complete/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/washer/wash/[sessionId]/complete">> = Specific
  const handler = {} as typeof import("../../src/app/(washer)/washer/wash/[sessionId]/complete/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(washer)/washer/wash/[sessionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/washer/wash/[sessionId]">> = Specific
  const handler = {} as typeof import("../../src/app/(washer)/washer/wash/[sessionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sign-in/[[...sign-in]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-in/[[...sign-in]]">> = Specific
  const handler = {} as typeof import("../../src/app/sign-in/[[...sign-in]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sign-up/[[...sign-up]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-up/[[...sign-up]]">> = Specific
  const handler = {} as typeof import("../../src/app/sign-up/[[...sign-up]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/analytics/revenue/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/revenue">> = Specific
  const handler = {} as typeof import("../../src/app/api/analytics/revenue/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/exports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exports">> = Specific
  const handler = {} as typeof import("../../src/app/api/exports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/locale/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locale">> = Specific
  const handler = {} as typeof import("../../src/app/api/locale/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/locations/[id]/availability/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locations/[id]/availability">> = Specific
  const handler = {} as typeof import("../../src/app/api/locations/[id]/availability/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/scheduling/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scheduling/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/scheduling/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscribe">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/mercadopago/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/mercadopago">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/mercadopago/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/stripe">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(admin)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(customer)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(customer)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(manager)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(manager)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(washer)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(washer)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
